/**:
  ros__parameters:
    enable_whole_load: true
    enable_downsampled_whole_load: true
    enable_partial_load: true
    enable_selected_load: false
    # only used when downsample_whole_load enabled
    leaf_size: 0.5  # downsample leaf size [m]
    pcd_paths_or_directory: ["/home/star/autoware/data/map_loader/output_kitti_05/pointcloud_map.pcd/"] # Path to the pointcloud map file or directory
    pcd_metadata_path: "/home/star/autoware/data/map_loader/output_kitti_05/pointcloud_map_metadata.yaml" # Path to pointcloud metadata file
